export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "SR Digi School",
    type: "School",
    location: "KPHB",
    companyName: "No.3 in Hyderabad",
    companyUrl: "Google.com",
    skills: ["4.2⭐", "1st-10th","SSC"],
    link: "https://sru.edu.in/",
    img:"https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Silver Oak's International School",
    type: "School",
    location: "Bachupally",
    companyName: "No.2 in Telangana",
    companyUrl: "Yahoo.com",
    skills: ["4.6⭐", "School","CBSE"],
    link: "https://www.silveroaks.co.in/home/hyderabad/",
    img:"https://images.unsplash.com/photo-1522770179533-24471fcdba45",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "VIKAS HIGH SCHOOL",
    type: "School",
    location: "KPHB",
    companyName: "No.7 in Telangana",
    companyUrl: "https://facebook.com",
    skills: ["4.3⭐","School","CBSE"],
    link: "https://www.vikasconcept.com/",
    img:"https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Narayana",
    type: "Intermediate",
    location: "Madhapur",
    companyName: "No.1 in Telangana",
    companyUrl: "https://microsoft.com",
    skills: ["4.8⭐","11th-12th","SSC"],
    link: "https://www.narayanagroup.com/",
    img:"https://images.unsplash.com/photo-1533827432537-70133748f5c8",
  },
  {
    id: 5,
    postedOn: new Date(),
    title: "EKASHILA",
    type: "SCHOOL",
    location: "Gandipet",
    companyName: "No.3 in Telangana",
    companyUrl: "hhttps://srichaitanya.net/",
    skills: ["4.5⭐","Sschol","SSC"],
    link: "https://www.cbit.ac.in/",
    img:"https://images.unsplash.com/photo-1558642452-9d2a7deb7f62",
  },
  {
    id: 6,
    postedOn: new Date(),
    title: "SPR School of Excellence",
    type: "School",
    location: "Uppal",
    companyName: "No.4 in Hyderabad",
    companyUrl: "https://infosys.com",
    skills: ["3.9⭐","6th-10th"],
    link: "https://sprschoolhnk.com/",
    img:"https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
  },
  {
    id: 7,
    postedOn: new Date(),
    title: "Sri Chaitanya",
    type: "Inter",
    location: "Nagole",
    companyName: "No.2 in Hyderabad",
    companyUrl: "https://facebook.com",
    skills: ["4.2⭐","11th-12th"],
    link: "https://facebook.com/careers",
    img:"https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
  },
  {
    id: 1,
    postedOn: new Date(),
    title: "SR Digi School",
    type: "School",
    location: "KPHB",
    companyName: "No.3 in Hyderabad",
    companyUrl: "Google.com",
    skills: ["4.2⭐", "1st-10th class"],
    link: "https://google.com/careers",
    img:"https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "VNR VJIET",
    type: "Engg",
    location: "Bachupally",
    companyName: "No.2 in Telangana",
    companyUrl: "Yahoo.com",
    skills: ["4.6⭐", "B.Tech/B.E"],
    link: "https://yahoo.com/jobs",
    img:"https://images.unsplash.com/photo-1522770179533-24471fcdba45",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "GRIET",
    type: "Engg",
    location: "KPHB",
    companyName: "No.7 in Telangana",
    companyUrl: "https://facebook.com",
    skills: ["4.3⭐","B.Tech/B.E"],
    link: "https://facebook.com/careers",
    img:"https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Narayana",
    type: "Intermediate",
    location: "Madhapur",
    companyName: "No.1 in Telangana",
    companyUrl: "https://microsoft.com",
    skills: ["4.8⭐","11th-12th"],
    link: "https://microsoft.com/careers",
    img:"https://images.unsplash.com/photo-1533827432537-70133748f5c8",
  },
  {
    id: 5,
    postedOn: new Date(),
    title: "CBIT",
    type: "Engg",
    location: "Gandipet",
    companyName: "No.3 in Telangana",
    companyUrl: "https://ibm.com",
    skills: ["4.5⭐","B.Tech/B.E"],
    link: "https://ibm.com/careers",
    img:"https://images.unsplash.com/photo-1558642452-9d2a7deb7f62",
  },
  {
    id: 6,
    postedOn: new Date(),
    title: "SPR School of Excellence",
    type: "School",
    location: "Uppal",
    companyName: "No.4 in Hyderabad",
    companyUrl: "https://infosys.com",
    skills: ["3.9⭐","6th-10th"],
    link: "https://infosys.com/careers",
    img:"https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
  },
  {
    id: 7,
    postedOn: new Date(),
    title: "Sri Chaitanya",
    type: "Inter",
    location: "Nagole",
    companyName: "No.2 in Hyderabad",
    companyUrl: "https://facebook.com",
    skills: ["4.2⭐","11th-12th"],
    link: "https://facebook.com/careers",
    img:"https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
  },
  {
    id: 1,
    postedOn: new Date(),
    title: "SR Digi School",
    type: "School",
    location: "KPHB",
    companyName: "No.3 in Hyderabad",
    companyUrl: "Google.com",
    skills: ["4.2⭐", "1st-10th class"],
    link: "https://google.com/careers",
    img:"https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "VNR VJIET",
    type: "Engg",
    location: "Bachupally",
    companyName: "No.2 in Telangana",
    companyUrl: "Yahoo.com",
    skills: ["4.6⭐", "B.Tech/B.E"],
    link: "https://yahoo.com/jobs",
    img:"https://images.unsplash.com/photo-1522770179533-24471fcdba45",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "GRIET",
    type: "Engg",
    location: "KPHB",
    companyName: "No.7 in Telangana",
    companyUrl: "https://facebook.com",
    skills: ["4.3⭐","B.Tech/B.E"],
    link: "https://facebook.com/careers",
    img:"https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Narayana",
    type: "Intermediate",
    location: "Madhapur",
    companyName: "No.1 in Telangana",
    companyUrl: "https://microsoft.com",
    skills: ["4.8⭐","11th-12th"],
    link: "https://microsoft.com/careers",
    img:"https://images.unsplash.com/photo-1533827432537-70133748f5c8",
  },
  {
    id: 5,
    postedOn: new Date(),
    title: "CBIT",
    type: "Engg",
    location: "Gandipet",
    companyName: "No.3 in Telangana",
    companyUrl: "https://ibm.com",
    skills: ["4.5⭐","B.Tech/B.E"],
    link: "https://ibm.com/careers",
    img:"https://images.unsplash.com/photo-1558642452-9d2a7deb7f62",
  },
  {
    id: 6,
    postedOn: new Date(),
    title: "SPR School of Excellence",
    type: "School",
    location: "Uppal",
    companyName: "No.4 in Hyderabad",
    companyUrl: "https://infosys.com",
    skills: ["3.9⭐","6th-10th"],
    link: "https://infosys.com/careers",
    img:"https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
  },
  {
    id: 7,
    postedOn: new Date(),
    title: "Sri Chaitanya",
    type: "Inter",
    location: "Nagole",
    companyName: "No.2 in Hyderabad",
    companyUrl: "https://facebook.com",
    skills: ["4.2⭐","11th-12th"],
    link: "https://facebook.com/careers",
    img:"https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
  },
  {
    id: 1,
    postedOn: new Date(),
    title: "SR Digi School",
    type: "School",
    location: "KPHB",
    companyName: "No.3 in Hyderabad",
    companyUrl: "Google.com",
    skills: ["4.2⭐", "1st-10th class"],
    link: "https://google.com/careers",
    img:"https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "VNR VJIET",
    type: "Engg",
    location: "Bachupally",
    companyName: "No.2 in Telangana",
    companyUrl: "Yahoo.com",
    skills: ["4.6⭐", "B.Tech/B.E"],
    link: "https://yahoo.com/jobs",
    img:"https://images.unsplash.com/photo-1522770179533-24471fcdba45",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "GRIET",
    type: "Engg",
    location: "KPHB",
    companyName: "No.7 in Telangana",
    companyUrl: "https://facebook.com",
    skills: ["4.3⭐","B.Tech/B.E"],
    link: "https://facebook.com/careers",
    img:"https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Narayana",
    type: "Intermediate",
    location: "Madhapur",
    companyName: "No.1 in Telangana",
    companyUrl: "https://microsoft.com",
    skills: ["4.8⭐","11th-12th"],
    link: "https://microsoft.com/careers",
    img:"https://images.unsplash.com/photo-1533827432537-70133748f5c8",
  },
  {
    id: 5,
    postedOn: new Date(),
    title: "CBIT",
    type: "Engg",
    location: "Gandipet",
    companyName: "No.3 in Telangana",
    companyUrl: "https://ibm.com",
    skills: ["4.5⭐","B.Tech/B.E"],
    link: "https://ibm.com/careers",
    img:"https://images.unsplash.com/photo-1558642452-9d2a7deb7f62",
  },
  {
    id: 6,
    postedOn: new Date(),
    title: "SPR School of Excellence",
    type: "School",
    location: "Uppal",
    companyName: "No.4 in Hyderabad",
    companyUrl: "https://infosys.com",
    skills: ["3.9⭐","6th-10th"],
    link: "https://infosys.com/careers",
    img:"https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
  },
  {
    id: 7,
    postedOn: new Date(),
    title: "Sri Chaitanya",
    type: "Inter",
    location: "Nagole",
    companyName: "No.2 in Hyderabad",
    companyUrl: "https://facebook.com",
    skills: ["4.2⭐","11th-12th"],
    link: "https://facebook.com/careers",
    img:"https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
  },
];
